require "core/ultisnips"
require "lazy-setup"
-- require "core/cmp-setup"
require "core/vim-commentary"
require "core/vim-sandwich"
require "core/vim-snippets"
require "core/nvim-web-devicons"
require "core/nvim-tree"
require "core/nvim-hlslens"
require "core/wilder"
require "core/nvim-notify"
require "core/night-owl"
-- require "core/tokyonight"
-- require "core/markdown-preview"
require "core/vim-autoformat"
require "core/nvim-bqf"
require "core/hlsearch"

require "core/my"
-- require "core/YouCompleteMe"
-- require "core/cmp-setup"
require "core/AutoTools/make"
